declare module "*.png";

type CanvasData = {
  orientation: "portrait" | "landscape";
  width: number;
  height: number;
};
type ModelSprites = {
  loaded: boolean;
  reticule?: ImageBitmap;
  carrier?: Array<ImageBitmap>;
  battleship?: Array<ImageBitmap>;
  cruiser?: Array<ImageBitmap>;
  submarine?: Array<ImageBitmap>;
  destroyer?: Array<ImageBitmap>;
  waterTiles?: Array<ImageBitmap>;
  radarTiles?: Array<ImageBitmap>;
  damageTiles?: Array<ImageBitmap>;
  highlightTiles?: Array<ImageBitmap>;
  buttonTiles?: {
    green: Array<ImageBitmap>;
    red: Array<ImageBitmap>;
  };
};
type ModelSpritesLoaded = {
  loaded: boolean;
  reticule: ImageBitmap;
  carrier: Array<ImageBitmap>;
  battleship: Array<ImageBitmap>;
  cruiser: Array<ImageBitmap>;
  submarine: Array<ImageBitmap>;
  destroyer: Array<ImageBitmap>;
  waterTiles: Array<ImageBitmap>;
  radarTiles: Array<ImageBitmap>;
  damageTiles: Array<ImageBitmap>;
  highlightTiles: Array<ImageBitmap>;
  buttonTiles: {
    green: Array<ImageBitmap>;
    red: Array<ImageBitmap>;
  };
};
type TextSprites = {
  loaded: boolean;
  A?: ImageBitmap;
  B?: ImageBitmap;
  C?: ImageBitmap;
  D?: ImageBitmap;
  E?: ImageBitmap;
  F?: ImageBitmap;
  G?: ImageBitmap;
  H?: ImageBitmap;
  I?: ImageBitmap;
  J?: ImageBitmap;
  K?: ImageBitmap;
  L?: ImageBitmap;
  M?: ImageBitmap;
  N?: ImageBitmap;
  O?: ImageBitmap;
  P?: ImageBitmap;
  Q?: ImageBitmap;
  R?: ImageBitmap;
  S?: ImageBitmap;
  T?: ImageBitmap;
  U?: ImageBitmap;
  V?: ImageBitmap;
  W?: ImageBitmap;
  X?: ImageBitmap;
  Y?: ImageBitmap;
  Z?: ImageBitmap;
  a?: ImageBitmap;
  b?: ImageBitmap;
  c?: ImageBitmap;
  d?: ImageBitmap;
  e?: ImageBitmap;
  f?: ImageBitmap;
  g?: ImageBitmap;
  h?: ImageBitmap;
  i?: ImageBitmap;
  j?: ImageBitmap;
  k?: ImageBitmap;
  l?: ImageBitmap;
  m?: ImageBitmap;
  n?: ImageBitmap;
  o?: ImageBitmap;
  p?: ImageBitmap;
  q?: ImageBitmap;
  r?: ImageBitmap;
  s?: ImageBitmap;
  t?: ImageBitmap;
  u?: ImageBitmap;
  v?: ImageBitmap;
  w?: ImageBitmap;
  x?: ImageBitmap;
  y?: ImageBitmap;
  z?: ImageBitmap;
  "0"?: ImageBitmap;
  "1"?: ImageBitmap;
  "2"?: ImageBitmap;
  "3"?: ImageBitmap;
  "4"?: ImageBitmap;
  "5"?: ImageBitmap;
  "6"?: ImageBitmap;
  "7"?: ImageBitmap;
  "8"?: ImageBitmap;
  "9"?: ImageBitmap;
  "("?: ImageBitmap;
  ")"?: ImageBitmap;
  "!"?: ImageBitmap;
  "."?: ImageBitmap;
  ","?: ImageBitmap;
  ":"?: ImageBitmap;
  ";"?: ImageBitmap;
  "?"?: ImageBitmap;
};
type TextSpritesLoaded = {
  loaded: boolean;
  A: ImageBitmap;
  B: ImageBitmap;
  C: ImageBitmap;
  D: ImageBitmap;
  E: ImageBitmap;
  F: ImageBitmap;
  G: ImageBitmap;
  H: ImageBitmap;
  I: ImageBitmap;
  J: ImageBitmap;
  K: ImageBitmap;
  L: ImageBitmap;
  M: ImageBitmap;
  N: ImageBitmap;
  O: ImageBitmap;
  P: ImageBitmap;
  Q: ImageBitmap;
  R: ImageBitmap;
  S: ImageBitmap;
  T: ImageBitmap;
  U: ImageBitmap;
  V: ImageBitmap;
  W: ImageBitmap;
  X: ImageBitmap;
  Y: ImageBitmap;
  Z: ImageBitmap;
  a: ImageBitmap;
  b: ImageBitmap;
  c: ImageBitmap;
  d: ImageBitmap;
  e: ImageBitmap;
  f: ImageBitmap;
  g: ImageBitmap;
  h: ImageBitmap;
  i: ImageBitmap;
  j: ImageBitmap;
  k: ImageBitmap;
  l: ImageBitmap;
  m: ImageBitmap;
  n: ImageBitmap;
  o: ImageBitmap;
  p: ImageBitmap;
  q: ImageBitmap;
  r: ImageBitmap;
  s: ImageBitmap;
  t: ImageBitmap;
  u: ImageBitmap;
  v: ImageBitmap;
  w: ImageBitmap;
  x: ImageBitmap;
  y: ImageBitmap;
  z: ImageBitmap;
  "0": ImageBitmap;
  "1": ImageBitmap;
  "2": ImageBitmap;
  "3": ImageBitmap;
  "4": ImageBitmap;
  "5": ImageBitmap;
  "6": ImageBitmap;
  "7": ImageBitmap;
  "8": ImageBitmap;
  "9": ImageBitmap;
  "(": ImageBitmap;
  ")": ImageBitmap;
  "!": ImageBitmap;
  ".": ImageBitmap;
  ",": ImageBitmap;
  ":": ImageBitmap;
  ";": ImageBitmap;
  "?": ImageBitmap;
};

type validTextSpriteAccessor =
  | "A"
  | "B"
  | "C"
  | "D"
  | "E"
  | "F"
  | "G"
  | "H"
  | "I"
  | "J"
  | "K"
  | "L"
  | "M"
  | "N"
  | "O"
  | "P"
  | "Q"
  | "R"
  | "S"
  | "T"
  | "U"
  | "V"
  | "W"
  | "X"
  | "Y"
  | "Z"
  | "a"
  | "b"
  | "c"
  | "d"
  | "e"
  | "f"
  | "g"
  | "h"
  | "i"
  | "j"
  | "k"
  | "l"
  | "m"
  | "n"
  | "o"
  | "p"
  | "q"
  | "r"
  | "s"
  | "t"
  | "u"
  | "v"
  | "w"
  | "x"
  | "y"
  | "z"
  | "0"
  | "1"
  | "2"
  | "3"
  | "4"
  | "5"
  | "6"
  | "7"
  | "8"
  | "9"
  | "("
  | ")"
  | "!"
  | "."
  | ","
  | ":"
  | ";"
  | "?";
